// Pasta shape database.
// method: extruded | rolled | hand | stamped

const PASTA = [
  // ---------------- LONG STRANDS ----------------
  {
    id: 'spaghetti',
    name: 'Spaghetti',
    pron: 'spah-GET-tee',
    meaning: '"Little strings" — from spago, twine.',
    cat: 'long',
    region: 'Naples, Campania',
    icon: 'strand',
    cook: '8–10 min',
    method: 'extruded',
    sauces: ['light', 'seafood', 'chunky', 'cheesy'],
    best: 'Oil- and tomato-based sauces that coat rather than cling. Aglio e olio, cacio e pepe, carbonara, vongole.',
    made: 'Semolina and water are kneaded into a crumbly dough, then forced under roughly 100 bar of pressure through a round die. The strands come out continuously and are cut to length by a rotating blade sitting right at the die face, then hung on rods to dry.',
    die: 'A flat bronze plate drilled with hundreds of simple round holes, about 1.8 mm across.',
    fact: 'Spaghetti was eaten with the hands in Naples well into the 1800s — the fork with a curved fourth tine was invented specifically so the king could eat it at the table.'
  },
  {
    id: 'spaghettini',
    name: 'Spaghettini',
    pron: 'spah-get-TEE-nee',
    meaning: '"Little spaghetti."',
    cat: 'long',
    region: 'Southern Italy',
    icon: 'strand-thin',
    cook: '5–7 min',
    method: 'extruded',
    sauces: ['light', 'seafood'],
    best: 'Delicate sauces — lemon and oil, anchovy, light shellfish. Too thin to carry anything heavy.',
    made: 'Identical process to spaghetti, just a narrower die hole. The thinner the strand, the faster it must be dried and the more fragile it is coming off the extruder.',
    die: 'Round holes around 1.6 mm.',
    fact: 'The number on Italian pasta boxes (No. 3, No. 5) is a die-size code, not a brand flourish.'
  },
  {
    id: 'capellini',
    name: 'Capellini / Angel Hair',
    pron: 'kah-pel-LEE-nee',
    meaning: '"Little hairs."',
    cat: 'long',
    region: 'Genoa & Naples',
    icon: 'strand-fine',
    cook: '2–4 min',
    method: 'extruded',
    sauces: ['light', 'brothy'],
    best: 'Barely-there sauces, or dropped into broth. It overcooks in the time it takes to drain it.',
    made: 'Extruded through the smallest practical round die. So fine that it is usually gathered into nests before drying, because loose strands would shatter.',
    die: 'Round holes under 1 mm.',
    fact: 'Angel hair keeps cooking hard from residual heat — pull it a full minute before you think you should.'
  },
  {
    id: 'bucatini',
    name: 'Bucatini',
    pron: 'boo-kah-TEE-nee',
    meaning: 'From buco, "hole."',
    cat: 'long',
    region: 'Lazio & Abruzzo',
    icon: 'strand-hollow',
    cook: '9–12 min',
    method: 'extruded',
    sauces: ['chunky', 'meaty', 'cheesy'],
    best: 'Amatriciana, above all. Also cacio e pepe and rich tomato sauces that can run up the middle.',
    made: 'The trick is in the die. Each hole has a tiny steel pin suspended in its center, held by thin bridges. Dough splits around the pin and fuses back together just past it, leaving a continuous channel down the strand.',
    die: 'Round hole about 3 mm with a centered pin — the bridge marks sometimes leave faint lines on the finished strand.',
    fact: 'Because the hole must not collapse, bucatini is extruded slower and dried gentler than spaghetti — which is part of why it costs more.'
  },
  {
    id: 'linguine',
    name: 'Linguine',
    pron: 'lin-GWEE-neh',
    meaning: '"Little tongues."',
    cat: 'long',
    region: 'Liguria',
    icon: 'strand-flat',
    cook: '9–11 min',
    method: 'extruded',
    sauces: ['seafood', 'pesto', 'light'],
    best: 'Pesto Genovese and clam sauce. The flat face gives oil something to hold onto.',
    made: 'Extruded through a flattened oval slot rather than a circle. The dough leaves the die already lens-shaped; no rolling or cutting is involved.',
    die: 'Elliptical slots roughly 3 mm wide by 1.4 mm thick.',
    fact: 'Linguine is the extruded answer to a ribbon — same silhouette as tagliatelle, completely different manufacture and bite.'
  },
  {
    id: 'pici',
    name: 'Pici',
    pron: 'PEE-chee',
    meaning: 'From appiciare, "to stick together."',
    cat: 'long',
    region: 'Siena, Tuscany',
    icon: 'strand-thick',
    cook: '6–9 min (fresh)',
    method: 'hand',
    sauces: ['chunky', 'meaty', 'cheesy'],
    best: 'Aglione (fat garlic and tomato), wild boar ragù, or just breadcrumbs and oil.',
    made: 'Not extruded at all. Flour-and-water dough is cut into strips and each one is rolled out under the palms into a fat, uneven strand. The irregularity is the point — every piece cooks slightly differently.',
    die: 'None. Two hands and a wooden board.',
    fact: 'Traditionally an eggless "poor" pasta — flour, water, a little oil. The thickness meant a small amount of flour fed a lot of people.'
  },
  {
    id: 'bigoli',
    name: 'Bigoli',
    pron: 'BEE-go-lee',
    meaning: 'From bigat, Venetian for "caterpillar."',
    cat: 'long',
    region: 'Veneto',
    icon: 'strand-thick',
    cook: '8–12 min',
    method: 'extruded',
    sauces: ['seafood', 'meaty'],
    best: 'Bigoli in salsa — onions melted down with anchovies. Also duck ragù.',
    made: 'Pressed through a bigolaro, a hand-cranked bronze press clamped to a bench. It is a true extruder, just human-powered: you turn a screw and thick rough strands push out the bottom.',
    die: 'Bronze plate, holes around 3 mm, always bronze — the drag is what makes the surface grip.',
    fact: 'Often made with whole wheat and sometimes duck egg, which is why bigoli is browner than most fresh pasta.'
  },

  // ---------------- RIBBONS ----------------
  {
    id: 'tagliatelle',
    name: 'Tagliatelle',
    pron: 'tal-yah-TEL-leh',
    meaning: 'From tagliare, "to cut."',
    cat: 'ribbon',
    region: 'Emilia-Romagna',
    icon: 'ribbon',
    cook: '2–4 min (fresh)',
    method: 'rolled',
    sauces: ['meaty', 'creamy', 'chunky'],
    best: 'Ragù alla Bolognese. This is the correct pasta for it, not spaghetti.',
    made: 'Egg dough is laminated — passed repeatedly through rollers at decreasing gaps until it is a thin sheet — then loosely rolled and sliced into ribbons with a knife or a cutting roller.',
    die: 'No die. Rollers and a blade.',
    fact: 'The Bolognese chamber of commerce deposited a golden ribbon at the city hall in 1972 defining the legal width: 8 mm cooked, 7 mm raw.'
  },
  {
    id: 'fettuccine',
    name: 'Fettuccine',
    pron: 'fet-too-CHEE-neh',
    meaning: '"Little ribbons."',
    cat: 'ribbon',
    region: 'Rome & Tuscany',
    icon: 'ribbon',
    cook: '3–5 min (fresh)',
    method: 'rolled',
    sauces: ['creamy', 'cheesy', 'meaty'],
    best: 'Butter and Parmigiano emulsified with pasta water. Cream sauces generally.',
    made: 'Same lamination-and-cut method as tagliatelle, cut slightly wider and usually a touch thicker. Dried supermarket versions are extruded through a wide flat slot instead.',
    die: 'Rollers for fresh; a rectangular slot die for dried.',
    fact: 'Alfredo di Lelio invented his version in Rome in 1908 with no cream at all — just butter, cheese and starchy water.'
  },
  {
    id: 'pappardelle',
    name: 'Pappardelle',
    pron: 'pap-par-DEL-leh',
    meaning: 'From pappare, "to gobble."',
    cat: 'ribbon',
    region: 'Tuscany',
    icon: 'ribbon-wide',
    cook: '3–5 min (fresh)',
    method: 'rolled',
    sauces: ['meaty', 'chunky'],
    best: 'Slow-braised game — wild boar, hare, beef shin. Big surface for a heavy sauce.',
    made: 'Rolled sheet cut into broad straps two to three centimetres wide, often with a fluted wheel that leaves a wavy edge.',
    die: 'No die. Sheet and a crimping cutter.',
    fact: 'The wavy edge is not decoration — the ruffles trap fragments of meat that a straight edge would let slide off.'
  },
  {
    id: 'mafaldine',
    name: 'Mafaldine / Reginette',
    pron: 'mah-fal-DEE-neh',
    meaning: 'Named for Princess Mafalda of Savoy.',
    cat: 'ribbon',
    region: 'Naples',
    icon: 'ribbon-ruffle',
    cook: '8–10 min',
    method: 'extruded',
    sauces: ['creamy', 'chunky', 'meaty'],
    best: 'Ricotta-based sauces, Neapolitan ragù, anything that can settle into the frills.',
    made: 'Extruded through a wide slot whose long edges are cut into a repeating wave. The dough emerges as a flat band already ruffled on both sides.',
    die: 'Rectangular slot about 12 mm wide with scalloped edges.',
    fact: 'Made as a tribute to the Italian princess — the ruffled edge is meant to suggest a crown.'
  },
  {
    id: 'lasagne',
    name: 'Lasagne',
    pron: 'lah-ZAHN-yeh',
    meaning: 'From Greek lasanon, "cooking pot."',
    cat: 'ribbon',
    region: 'Emilia-Romagna',
    icon: 'sheet',
    cook: '2 min (fresh) or bake',
    method: 'rolled',
    sauces: ['baked', 'meaty', 'creamy'],
    best: 'Layering, obviously. Ragù and besciamella.',
    made: 'Rolled sheets cut to rectangles. Dried commercial sheets are extruded flat through a very wide slot, then cut and dried on trays rather than hung.',
    die: 'A wide flat slot, or none at all for fresh.',
    fact: 'One of the oldest pasta shapes in Europe — flat baked sheets are documented in Italy before forks were common.'
  },

  // ---------------- TUBES ----------------
  {
    id: 'penne-rigate',
    name: 'Penne Rigate',
    pron: 'PEN-neh ree-GAH-teh',
    meaning: '"Ridged quills."',
    cat: 'tube',
    region: 'Liguria / Campania',
    icon: 'penne',
    cook: '10–12 min',
    method: 'extruded',
    sauces: ['chunky', 'creamy', 'baked', 'meaty'],
    best: 'Arrabbiata, vodka sauce, anything chunky enough to lodge inside the tube.',
    made: 'A tube is extruded through a ring-shaped die opening — an outer circle with a center pin. Grooves in the die wall cut the ridges. The signature diagonal ends come from a blade angled at roughly 45° to the tube as it exits.',
    die: 'Annular opening about 8 mm outer diameter, with longitudinal grooves and an angled cutter.',
    fact: 'Giovanni Battista Capurro patented the diagonal cutting machine in 1865 in Liguria. Before that, cutting tubes on the bias by hand crushed them.'
  },
  {
    id: 'penne-lisce',
    name: 'Penne Lisce',
    pron: 'PEN-neh LEE-sheh',
    meaning: '"Smooth quills."',
    cat: 'tube',
    region: 'Campania',
    icon: 'penne-smooth',
    cook: '10–12 min',
    method: 'extruded',
    sauces: ['creamy', 'light'],
    best: 'Silky, emulsified sauces that don\'t need gripping. Divisive — many Italians consider it inferior.',
    made: 'Same as penne rigate but with a smooth die wall. Extrudes faster and dries more evenly, which is why factories like it.',
    die: 'Annular opening, no grooves, angled cutter.',
    fact: 'Smooth pasta and Teflon dies go together: both give a glossy surface that sauce slides off. Bronze dies plus ridges are the opposite philosophy.'
  },
  {
    id: 'rigatoni',
    name: 'Rigatoni',
    pron: 'ree-gah-TOH-nee',
    meaning: 'From rigato, "ridged."',
    cat: 'tube',
    region: 'Rome & Southern Italy',
    icon: 'rigatoni',
    cook: '11–13 min',
    method: 'extruded',
    sauces: ['meaty', 'chunky', 'baked', 'cheesy'],
    best: 'Ragù, carbonara alternatives, pasta al forno. The wide bore swallows sauce.',
    made: 'Extruded through a large annular die with deep grooves, then cut square across rather than on the diagonal.',
    die: 'Annular opening 12–15 mm outer diameter, deeply grooved, straight cutter.',
    fact: 'Rigatoni holds its shape in the oven better than almost any other tube — the ridges add structural rigidity, not just grip.'
  },
  {
    id: 'paccheri',
    name: 'Paccheri',
    pron: 'PAK-keh-ree',
    meaning: 'From Neapolitan paccharia, "slaps."',
    cat: 'tube',
    region: 'Campania & Calabria',
    icon: 'paccheri',
    cook: '12–15 min',
    method: 'extruded',
    sauces: ['seafood', 'chunky', 'baked'],
    best: 'Seafood, or stuffed and baked standing upright. They collapse dramatically on the plate.',
    made: 'A very large smooth tube extruded through a wide annular die. The walls are thin relative to the diameter, so extrusion pressure and drying must be carefully controlled or they crack.',
    die: 'Annular opening around 25–30 mm outer diameter.',
    fact: 'The name refers to the slapping noise they make when they hit the plate and flatten.'
  },
  {
    id: 'ziti',
    name: 'Ziti',
    pron: 'ZEE-tee',
    meaning: 'From zita, "bride" — wedding pasta.',
    cat: 'tube',
    region: 'Campania & Sicily',
    icon: 'ziti',
    cook: '11–13 min',
    method: 'extruded',
    sauces: ['baked', 'meaty', 'cheesy'],
    best: 'Baked ziti. Neapolitan ragù that has cooked for six hours.',
    made: 'Extruded as long smooth tubes. Traditionally sold as long rods that were snapped by hand before cooking, not pre-cut.',
    die: 'Annular opening about 10 mm, smooth walls.',
    fact: 'Breaking the ziti by hand at the table was part of Sunday lunch in Naples — the pieces were meant to be uneven.'
  },
  {
    id: 'macaroni',
    name: 'Maccheroni / Elbows',
    pron: 'mah-keh-ROH-nee',
    meaning: 'Possibly from maccare, "to crush."',
    cat: 'tube',
    region: 'Southern Italy',
    icon: 'elbow',
    cook: '7–9 min',
    method: 'extruded',
    sauces: ['cheesy', 'baked', 'creamy'],
    best: 'Mac and cheese. Cold pasta salads. Soups.',
    made: 'The curve is an accident of physics, engineered on purpose: one side of the die opening is slightly restricted, so dough exits faster on one side than the other and the tube bends as it leaves.',
    die: 'Annular opening with an asymmetric gap that biases flow to one side.',
    fact: 'Change the asymmetry and you change the curve — the same principle produces chifferi, gomiti and lumache.'
  },
  {
    id: 'ditalini',
    name: 'Ditalini',
    pron: 'dee-tah-LEE-nee',
    meaning: '"Little thimbles."',
    cat: 'tube',
    region: 'Sicily & Campania',
    icon: 'ditalini',
    cook: '8–10 min',
    method: 'extruded',
    sauces: ['brothy', 'chunky'],
    best: 'Pasta e fagioli, minestrone, pasta e ceci. Soup pasta first and foremost.',
    made: 'Small tubes extruded through a compact annular die and chopped very short by a fast blade — the cutter runs at high speed relative to the extrusion rate.',
    die: 'Annular opening about 5 mm, cut every few millimetres.',
    fact: 'Cutter speed alone separates ditalini from ziti. Same die family, different blade rhythm.'
  },
  {
    id: 'mezze-maniche',
    name: 'Mezze Maniche',
    pron: 'MET-seh MAH-nee-keh',
    meaning: '"Half sleeves."',
    cat: 'tube',
    region: 'Rome',
    icon: 'mezze-maniche',
    cook: '10–12 min',
    method: 'extruded',
    sauces: ['meaty', 'cheesy', 'chunky'],
    best: 'Carbonara, gricia, amatriciana — the Roman canon.',
    made: 'Essentially short rigatoni: wide grooved tube, straight cut, but only about half the length.',
    die: 'Annular opening 12 mm, grooved, fast straight cutter.',
    fact: 'Many Roman trattorias prefer this to spaghetti for carbonara because the egg sauce collects inside each tube.'
  },
  {
    id: 'garganelli',
    name: 'Garganelli',
    pron: 'gar-gah-NEL-lee',
    meaning: 'From garganel, dialect for "chicken gullet."',
    cat: 'tube',
    region: 'Emilia-Romagna',
    icon: 'garganelli',
    cook: '3–5 min (fresh)',
    method: 'hand',
    sauces: ['creamy', 'meaty'],
    best: 'Prosciutto and pea cream sauce, or a light ragù.',
    made: 'Not extruded. Squares of egg dough are rolled diagonally around a thin dowel and pressed over a ridged wooden comb (a pettine), which grooves the outside and seals the seam.',
    die: 'None — a dowel and a ridged comb.',
    fact: 'The diagonal roll means the ridges run at an angle, which is how you can tell real garganelli from a penne impostor.'
  },
  {
    id: 'cannelloni',
    name: 'Cannelloni',
    pron: 'kah-neh-LOH-nee',
    meaning: '"Large reeds."',
    cat: 'tube',
    region: 'Emilia-Romagna & Piedmont',
    icon: 'cannelloni',
    cook: 'Bake 25–35 min',
    method: 'rolled',
    sauces: ['baked', 'creamy', 'meaty'],
    best: 'Stuffed with ricotta and spinach or veal, blanketed in besciamella, baked.',
    made: 'Traditionally a flat sheet of egg pasta rolled around filling. Dried boxed versions are extruded as very wide smooth tubes and cut into lengths.',
    die: 'Annular opening around 25 mm for dried; no die for fresh.',
    fact: 'Fresh sheets give a better result than dried tubes — they hydrate from the sauce instead of fighting it.'
  },

  // ---------------- SHAPES ----------------
  {
    id: 'fusilli',
    name: 'Fusilli',
    pron: 'foo-ZEE-lee',
    meaning: 'From fuso, "spindle."',
    cat: 'shape',
    region: 'Campania & Molise',
    icon: 'fusilli',
    cook: '10–12 min',
    method: 'extruded',
    sauces: ['pesto', 'chunky', 'creamy'],
    best: 'Pesto, chunky vegetable sauces, pasta salad. The grooves are a trap for everything.',
    made: 'The die has an offset insert that forces the dough to rotate as it is pushed out — the strand twists itself into a helix on the way through. No mechanical twisting happens after extrusion.',
    die: 'A slot with a helical or offset obstruction that induces spin.',
    fact: 'Hand-made fusilli is the older method: a strip of dough wrapped around a thin iron rod called a ferretto, then slid off.'
  },
  {
    id: 'rotini',
    name: 'Rotini',
    pron: 'roh-TEE-nee',
    meaning: '"Little wheels" / spirals.',
    cat: 'shape',
    region: 'Southern Italy / Italian-American',
    icon: 'rotini',
    cook: '8–10 min',
    method: 'extruded',
    sauces: ['chunky', 'creamy', 'baked'],
    best: 'Pasta salad, baked casseroles, thick tomato sauces.',
    made: 'Same principle as fusilli but a tighter, more corkscrewed helix from a more aggressive die insert.',
    die: 'Twisted slot die, tighter pitch than fusilli.',
    fact: 'Rotini and fusilli are used interchangeably in most of the world; in Italy the distinction is the tightness of the spiral.'
  },
  {
    id: 'cavatappi',
    name: 'Cavatappi',
    pron: 'kah-vah-TAP-pee',
    meaning: '"Corkscrews."',
    cat: 'shape',
    region: 'Southern Italy',
    icon: 'cavatappi',
    cook: '8–10 min',
    method: 'extruded',
    sauces: ['cheesy', 'creamy', 'baked'],
    best: 'Grown-up mac and cheese. Sauce goes inside and outside at once.',
    made: 'A hollow tube extruded through a ring die that is simultaneously spun, so the tube coils as it emerges. It is one of the harder shapes to make — the tube must curl without collapsing.',
    die: 'Annular opening with rotational bias, ridged.',
    fact: 'Cavatappi is the only common shape that is both a tube and a spiral, which is why it holds more sauce per gram than almost anything else.'
  },
  {
    id: 'farfalle',
    name: 'Farfalle',
    pron: 'far-FAL-leh',
    meaning: '"Butterflies."',
    cat: 'shape',
    region: 'Lombardy & Emilia-Romagna',
    icon: 'farfalle',
    cook: '10–12 min',
    method: 'stamped',
    sauces: ['creamy', 'light', 'chunky'],
    best: 'Cream and pea sauces, salmon, cold salads.',
    made: 'Cannot be extruded. A sheet of dough is cut into rectangles with a fluted wheel, then a machine pinches each rectangle at the center. The pinch is a mechanical crimp, not a mold.',
    die: 'None — a crimping cutter and a pinching mechanism.',
    fact: 'The double thickness at the pinch cooks slower than the wings, so farfalle is never uniformly al dente. That is inherent to the shape.'
  },
  {
    id: 'conchiglie',
    name: 'Conchiglie',
    pron: 'kon-KEEL-yeh',
    meaning: '"Shells."',
    cat: 'shape',
    region: 'Campania',
    icon: 'shell',
    cook: '10–12 min',
    method: 'extruded',
    sauces: ['chunky', 'creamy', 'baked'],
    best: 'Anything with small pieces — sausage, peas, ricotta. Large ones get stuffed and baked.',
    made: 'Extruded as a curved ridged strip through a crescent-shaped die slot, then cut. Residual stress in the dough makes the strip curl into a cup as it leaves the die.',
    die: 'Crescent slot, ridged on the outer face.',
    fact: 'The curl is not stamped in. It happens because the outer edge of the crescent moves faster than the inner edge, exactly like the elbow macaroni trick.'
  },
  {
    id: 'lumache',
    name: 'Lumache',
    pron: 'loo-MAH-keh',
    meaning: '"Snails."',
    cat: 'shape',
    region: 'Southern Italy',
    icon: 'lumache',
    cook: '11–13 min',
    method: 'extruded',
    sauces: ['chunky', 'cheesy', 'baked'],
    best: 'Thick ragù, cheese sauces, baked dishes. The opening scoops.',
    made: 'A ridged tube extruded with a strong one-sided flow bias so it curls almost into a full circle, then cut short.',
    die: 'Annular opening with heavy asymmetry and grooves.',
    fact: 'Considered by many Roman cooks the ideal carbonara shape — better than any straight tube at catching egg.'
  },
  {
    id: 'orecchiette',
    name: 'Orecchiette',
    pron: 'oh-rek-KYET-teh',
    meaning: '"Little ears."',
    cat: 'shape',
    region: 'Puglia',
    icon: 'ear',
    cook: '10–13 min',
    method: 'hand',
    sauces: ['chunky', 'light', 'meaty'],
    best: 'Cime di rapa with anchovy and garlic. Also sausage and broccoli.',
    made: 'Never extruded traditionally. A rope of semolina dough is cut into discs, each one dragged across a wooden board with a knife to curl it, then flipped over a thumb. The dragged side is rough, the thumb side smooth.',
    die: 'None — a knife, a board and a thumb.',
    fact: 'On Via dell\'Arco Basso in Bari, women still make and sell them on the street. Industrial versions press dough into molds, which is why they never quite match.'
  },
  {
    id: 'trofie',
    name: 'Trofie',
    pron: 'TROH-fyeh',
    meaning: 'From Ligurian strofinare, "to rub."',
    cat: 'shape',
    region: 'Liguria',
    icon: 'twist',
    cook: '5–8 min',
    method: 'hand',
    sauces: ['pesto', 'light'],
    best: 'Pesto Genovese with potato and green beans. That is the dish.',
    made: 'A small piece of dough is rolled under the side of the palm on a board so it stretches and twists at the same time, producing a short tapered spiral with a seam down it.',
    die: 'None — palm and board.',
    fact: 'Made with flour and water only, no egg. Ligurian pesto tradition treats egg pasta as too rich for basil.'
  },
  {
    id: 'gemelli',
    name: 'Gemelli',
    pron: 'jeh-MEL-lee',
    meaning: '"Twins."',
    cat: 'shape',
    region: 'Southern Italy',
    icon: 'twist',
    cook: '9–11 min',
    method: 'extruded',
    sauces: ['chunky', 'pesto', 'creamy'],
    best: 'Pesto, chunky vegetable sauces, salads.',
    made: 'Despite the name, it is a single strand. The die extrudes one solid rod that twists back on itself as it exits, creating the illusion of two strands twisted together.',
    die: 'A single slot with a rotational insert.',
    fact: 'Cut a gemelli in half and the cross-section proves it — one piece of dough, not two.'
  },
  {
    id: 'casarecce',
    name: 'Casarecce',
    pron: 'kah-sah-RETCH-eh',
    meaning: '"Homemade."',
    cat: 'shape',
    region: 'Sicily',
    icon: 'casarecce',
    cook: '9–11 min',
    method: 'extruded',
    sauces: ['chunky', 'pesto', 'meaty'],
    best: 'Pesto alla Trapanese, aubergine and tomato, sausage ragù.',
    made: 'Extruded as a narrow S-shaped strip that rolls in on itself along its length, forming a loose scroll with a groove down the middle.',
    die: 'A narrow S or hook-profile slot.',
    fact: 'The open channel down the length behaves like a very short tube — it catches oil and small solids that a solid twist would shed.'
  },
  {
    id: 'strozzapreti',
    name: 'Strozzapreti',
    pron: 'strot-sah-PREH-tee',
    meaning: '"Priest stranglers."',
    cat: 'shape',
    region: 'Emilia-Romagna & Umbria',
    icon: 'twist',
    cook: '8–10 min',
    method: 'hand',
    sauces: ['meaty', 'chunky'],
    best: 'Sausage ragù, tomato and pancetta, hearty vegetable sauces.',
    made: 'A strip of dough is rolled between the palms with a quick rubbing motion so it twists irregularly, then snapped off. Commercial versions extrude an approximation.',
    die: 'None traditionally; a twisted flat slot for dried versions.',
    fact: 'Several competing stories about the name; the least gruesome is that housewives made them while cursing greedy clergy.'
  },
  {
    id: 'cavatelli',
    name: 'Cavatelli',
    pron: 'kah-vah-TEL-lee',
    meaning: 'From cavare, "to hollow out."',
    cat: 'shape',
    region: 'Molise & Puglia',
    icon: 'cavatelli',
    cook: '8–12 min',
    method: 'hand',
    sauces: ['chunky', 'meaty', 'light'],
    best: 'Broccoli rabe and sausage, ricotta and tomato, beans.',
    made: 'Small pieces of semolina dough are pressed and dragged with two fingers or a knife across a board, hollowing each one into a little canoe with a rough dragged surface.',
    die: 'None — fingers and a board, or a hand-cranked cavatelli roller.',
    fact: 'Cavatelli and orecchiette come from the same dough and the same gesture; the difference is whether you flip it over your thumb at the end.'
  },
  {
    id: 'malloreddus',
    name: 'Malloreddus',
    pron: 'mah-loh-REH-doos',
    meaning: 'Sardinian for "little bulls."',
    cat: 'shape',
    region: 'Sardinia',
    icon: 'malloreddus',
    cook: '10–13 min',
    method: 'hand',
    sauces: ['meaty', 'chunky'],
    best: 'Alla Campidanese — sausage, tomato and saffron.',
    made: 'Semolina dough, often tinted with saffron, is rolled into small pieces and pressed against a ridged basket or grooved board so one face picks up deep parallel lines.',
    die: 'None — a ridged board (ciuliri) or basket.',
    fact: 'Also called gnocchetti sardi. The saffron in the dough is traditional, not a modern flourish.'
  },
  {
    id: 'radiatori',
    name: 'Radiatori',
    pron: 'rah-dee-ah-TOH-ree',
    meaning: '"Radiators."',
    cat: 'shape',
    region: '20th-century Italy',
    icon: 'radiator',
    cook: '9–11 min',
    method: 'extruded',
    sauces: ['chunky', 'creamy', 'baked'],
    best: 'Thick sauces and pasta salads. Enormous surface area.',
    made: 'One of the most complex dies in production: a compact profile with deep radial fins. Extrusion is slow because the dough has to fill every fin evenly without tearing.',
    die: 'Finned radial profile, cut very short.',
    fact: 'Reportedly designed in the 1960s by an industrial designer, inspired by car radiators — one of the few shapes with a documented modern origin.'
  },
  {
    id: 'rotelle',
    name: 'Rotelle / Wagon Wheels',
    pron: 'roh-TEL-leh',
    meaning: '"Little wheels."',
    cat: 'shape',
    region: 'Modern Italy',
    icon: 'wheel',
    cook: '9–11 min',
    method: 'extruded',
    sauces: ['chunky', 'baked', 'creamy'],
    best: 'Chunky sauces, kids\' dinners, salads.',
    made: 'Extruded through a die shaped like a wheel — an outer ring, a hub, and spokes between them — then sliced thin.',
    die: 'Wheel profile with a hub and radial spokes.',
    fact: 'The spokes are the weak point: extrude too fast and they tear, which is why rotelle boxes always contain some broken wheels.'
  },
  {
    id: 'campanelle',
    name: 'Campanelle',
    pron: 'kam-pah-NEL-leh',
    meaning: '"Little bells."',
    cat: 'shape',
    region: 'Modern Italy',
    icon: 'campanelle',
    cook: '9–11 min',
    method: 'extruded',
    sauces: ['creamy', 'chunky', 'cheesy'],
    best: 'Cream sauces and meat sauces — the bell fills up.',
    made: 'A ruffled strip is extruded and then curled into a cone as it exits, using the same differential-flow trick that curves macaroni, applied to a frilled profile.',
    die: 'Frilled crescent profile with flow bias.',
    fact: 'Also sold as gigli, "lilies" — same shape, different marketing.'
  },
  {
    id: 'gnocchi-sardi',
    name: 'Gnocchi (potato)',
    pron: 'NYOK-kee',
    meaning: 'From nocchio, "knot in wood."',
    cat: 'shape',
    region: 'Northern Italy',
    icon: 'gnocchi',
    cook: '2–3 min',
    method: 'hand',
    sauces: ['creamy', 'cheesy', 'meaty', 'light'],
    best: 'Butter and sage, gorgonzola, simple tomato. They are rich enough on their own.',
    made: 'Not really pasta in the extruded sense. Cooked riced potato is bound with a minimum of flour and egg, rolled into ropes, cut, and rolled down a ridged paddle or fork tines to groove them.',
    die: 'None — a gnocchi board or fork.',
    fact: 'Every gram of extra flour makes them tougher. Bake the potatoes instead of boiling to keep water out of the dough.'
  },

  // ---------------- SMALL / SOUP ----------------
  {
    id: 'orzo',
    name: 'Orzo / Risoni',
    pron: 'OR-tsoh',
    meaning: '"Barley," which it resembles.',
    cat: 'small',
    region: 'Southern Italy & Greece',
    icon: 'grain',
    cook: '7–9 min',
    method: 'extruded',
    sauces: ['brothy', 'light', 'baked'],
    best: 'Soups, pilaf-style dishes, cold salads with lemon and herbs.',
    made: 'Extruded through a small oval die and cut extremely short by a high-speed blade, then tumbled so the ends round off slightly during drying.',
    die: 'Small pointed-oval opening, roughly 2 × 5 mm.',
    fact: 'It behaves like rice because of the shape, not the ingredients — it is ordinary semolina pasta.'
  },
  {
    id: 'stelline',
    name: 'Stelline',
    pron: 'stel-LEE-neh',
    meaning: '"Little stars."',
    cat: 'small',
    region: 'Italy, widely',
    icon: 'star',
    cook: '5–6 min',
    method: 'extruded',
    sauces: ['brothy'],
    best: 'Chicken broth. Children\'s soup. Nothing else, really.',
    made: 'Extruded through a die cut with tiny star silhouettes, each with a center hole, and shaved off almost immediately by the cutter.',
    die: 'Star profile about 5 mm across with a center hole.',
    fact: 'The center hole exists so they cook evenly — without it the middle stays raw while the points go to mush.'
  },
  {
    id: 'acini-di-pepe',
    name: 'Acini di Pepe',
    pron: 'ah-CHEE-nee dee PEH-peh',
    meaning: '"Peppercorns."',
    cat: 'small',
    region: 'Southern Italy',
    icon: 'dots',
    cook: '5–7 min',
    method: 'extruded',
    sauces: ['brothy'],
    best: 'Italian wedding soup, brothy soups, the dessert salad called frog eye.',
    made: 'Extruded through the smallest round die and cut essentially flush with the die face, so each piece is a bead barely longer than it is wide.',
    die: 'Round holes about 1.5 mm, cutter running at maximum speed.',
    fact: 'The fastest cutter speed in the pasta factory. The blade is effectively scraping the die.'
  },
  {
    id: 'anelli',
    name: 'Anelli',
    pron: 'ah-NEL-lee',
    meaning: '"Rings."',
    cat: 'small',
    region: 'Sicily',
    icon: 'ring',
    cook: '7–9 min',
    method: 'extruded',
    sauces: ['brothy', 'baked'],
    best: 'Soups, and Sicilian anelletti al forno — baked with ragù, peas and caciocavallo.',
    made: 'Extruded as a thin tube and cut so short that each piece is a ring rather than a tube.',
    die: 'Small annular opening, cut nearly flush.',
    fact: 'Anelletti al forno is the classic Palermo picnic dish — it slices like a cake once it cools.'
  },
  {
    id: 'fregola',
    name: 'Fregola',
    pron: 'FREH-goh-lah',
    meaning: 'From fregare, "to rub."',
    cat: 'small',
    region: 'Sardinia',
    icon: 'dots',
    cook: '10–14 min',
    method: 'hand',
    sauces: ['brothy', 'seafood'],
    best: 'Clams and tomato, or a saffron broth.',
    made: 'Not extruded. Semolina is sprinkled with salted water in a wide bowl and rubbed by hand until it clumps into irregular beads, which are then sieved by size and toasted in an oven.',
    die: 'None — a bowl, water and hands.',
    fact: 'The toasting is what makes it: fregola is nutty and browned before it ever hits water, unlike any other pasta.'
  },

  // ---------------- FILLED ----------------
  {
    id: 'ravioli',
    name: 'Ravioli',
    pron: 'rah-vee-OH-lee',
    meaning: 'Possibly from rabiole, "leftovers."',
    cat: 'filled',
    region: 'All over Italy',
    icon: 'ravioli',
    cook: '3–5 min',
    method: 'stamped',
    sauces: ['light', 'creamy', 'cheesy'],
    best: 'Brown butter and sage, or a light tomato. Never drown filled pasta.',
    made: 'Two sheets of rolled egg dough with filling piped between them, pressed to expel air, then cut and sealed with a fluted stamp or wheel. Machines do the same thing with rollers and a rotary die.',
    die: 'A stamping die, not an extrusion die.',
    fact: 'Trapped air is the enemy — a bubble expands in boiling water and bursts the seal.'
  },
  {
    id: 'tortellini',
    name: 'Tortellini',
    pron: 'tor-tel-LEE-nee',
    meaning: 'From torta, "little cake."',
    cat: 'filled',
    region: 'Bologna & Modena',
    icon: 'tortellini',
    cook: '3–4 min',
    method: 'stamped',
    sauces: ['brothy', 'creamy'],
    best: 'In capon broth. In Bologna, serving them in cream is close to heresy.',
    made: 'Small squares of thin egg dough are filled, folded into a triangle, then wrapped around a fingertip and the two corners pressed together. Every one is folded individually.',
    die: 'None — a cutter for the squares, then hands.',
    fact: 'The official Bolognese filling is registered: pork loin, prosciutto, mortadella, Parmigiano, egg and nutmeg.'
  },
  {
    id: 'agnolotti',
    name: 'Agnolotti del Plin',
    pron: 'ah-nyoh-LOT-tee del PLEEN',
    meaning: 'Plin means "pinch" in Piedmontese.',
    cat: 'filled',
    region: 'Piedmont',
    icon: 'agnolotti',
    cook: '2–4 min',
    method: 'stamped',
    sauces: ['light', 'meaty'],
    best: 'Roast meat juices, or butter. Sometimes served on a napkin with nothing at all.',
    made: 'Filling is piped along a single strip of very thin dough, the dough is folded over, and each parcel is pinched shut between finger and thumb before being cut apart with a wheel.',
    die: 'None — a piping bag, fingers and a cutting wheel.',
    fact: 'Single sheet, not two — which is why they are thinner and more delicate than ravioli.'
  },
  {
    id: 'cappelletti',
    name: 'Cappelletti',
    pron: 'kap-pel-LET-tee',
    meaning: '"Little hats."',
    cat: 'filled',
    region: 'Romagna & Le Marche',
    icon: 'tortellini',
    cook: '3–4 min',
    method: 'stamped',
    sauces: ['brothy', 'creamy'],
    best: 'Broth at Christmas. Occasionally butter and Parmigiano.',
    made: 'Like tortellini but starting from a square rather than a round, folded corner to corner and then wrapped, giving a peaked crown instead of a smooth ring.',
    die: 'None — square cutter and hands.',
    fact: 'Cappelletti are typically filled with cheese, tortellini with meat. That, and the starting shape, is the whole difference.'
  },
  {
    id: 'mezzelune',
    name: 'Mezzelune',
    pron: 'met-seh-LOO-neh',
    meaning: '"Half moons."',
    cat: 'filled',
    region: 'Trentino-Alto Adige',
    icon: 'mezzelune',
    cook: '3–5 min',
    method: 'stamped',
    sauces: ['creamy', 'light'],
    best: 'Melted butter with poppy seeds, or sage. Common with beet or potato fillings.',
    made: 'Rounds are cut from a single sheet, filled off-center, folded over and sealed by hand or with a crimped press.',
    die: 'A round cutter and a crimping press.',
    fact: 'The Alpine versions are often filled with sauerkraut, beetroot or smoked ricotta — a very different tradition from the south.'
  }
];

const CATEGORIES = {
  long: { label: 'Long Strands', blurb: 'Extruded rods and rounds — the classic dried pasta.' },
  ribbon: { label: 'Ribbons & Sheets', blurb: 'Flat pasta, usually rolled and cut rather than extruded.' },
  tube: { label: 'Tubes', blurb: 'Hollow shapes made with a pin or ring in the die.' },
  shape: { label: 'Shaped & Twisted', blurb: 'Spirals, shells and curls — the hardest dies to engineer.' },
  small: { label: 'Small & Soup', blurb: 'Cut nearly flush at the die face. Made for broth.' },
  filled: { label: 'Filled', blurb: 'Never extruded. Sheets, filling and a seal.' }
};

const SAUCE_TAGS = {
  chunky: 'Chunky tomato & veg',
  creamy: 'Creamy',
  cheesy: 'Cheesy',
  meaty: 'Slow-cooked meat ragù',
  light: 'Light oil, garlic, lemon',
  seafood: 'Seafood',
  pesto: 'Pesto',
  brothy: 'Soup & broth',
  baked: 'Baked in the oven'
};

const METHODS = {
  extruded: 'Extruded through a die',
  rolled: 'Rolled & cut from a sheet',
  hand: 'Hand-formed',
  stamped: 'Filled & sealed'
};
